[theme]
primaryColor = "#000000"         # Color de botones y elementos activos
backgroundColor = "#ffd489"      # Fondo principal azul oscuro
secondaryBackgroundColor = "#9e2100"  # Fondo de contenedores
textColor = "#ffffff"            # Color de texto por defecto (blanco)
font = "sans serif"
